### ISSUE TITLE
cbsh 0.4.0 panics with ~/.cbsh/config using same value for bucket name and username 

### ISSUE THREAD

**Issue by mcarifio** [couchbaselabs/couchbase-shell#59]
cbsh (and couchbase) seem pretty cool. I'm new to both (but have followed nushell sporadically).

This issue might be a dupe. I've seen a few previous ones related to buckets, but they seem like variants of mine so I thought I'd capture this. If it _is_ a dupe, mark it as such.

When I state a "starting bucket" at the command line, it's not respected:

```bash
$ cbsh --bucket mcarifio
👤 mcarifio at 🏠 default
> use
───┬─────────┬───────────
 # │ cluster │  bucket   
───┼─────────┼───────────
 0 │ default │ <not set> 
───┴─────────┴───────────
👤 mcarifio at 🏠 default
> use bucket mcarifio
───┬──────────
 # │  bucket  
───┼──────────
 0 │ mcarifio 
───┴──────────
👤 mcarifio at 🏠 default in 🗄  mcarifio
> use
───┬─────────┬──────────
 # │ cluster │  bucket  
───┼─────────┼──────────
 0 │ default │ mcarifio 
───┴─────────┴──────────
```

If I state the `default-bucket` in `~/.cbsh/config`:

```
version = 1
[clusters.default]
hostnames = ["127.0.0.1"]
# panics cbsh if set?
default-bucket = "mcarifio"
username = "mcarifio"
```
and run:
```bash
cbsh
👤 mcarifio at 🏠 default in 🗄  mcarifio
>  ERROR couchbase::io::lcb::callbacks > The instance has been associated with the bucket already, sorry
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: 203', /home/runner/.cargo/git/checkouts/couchbase-rs-9bae2babc4d89f61/3a0f8d9/couchbase/src/io/lcb/mod.rs:111:54
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

👤 mcarifio at 🏠 default in 🗄  mcarifio
> use
───┬─────────┬──────────
 # │ cluster │  bucket  
───┼─────────┼──────────
 0 │ default │ mcarifio 
───┴─────────┴──────────

> nodes
thread 'main' panicked at 'Could not send request: "SendError(..)"', /home/runner/.cargo/git/checkouts/couchbase-rs-9bae2babc4d89f61/3a0f8d9/couchbase/src/io/lcb/mod.rs:54:14
thread 'main' panicked at 'Failure while shutting down!: "SendError(..)"', /home/runner/.cargo/git/checkouts/couchbase-rs-9bae2babc4d89f61/3a0f8d9/couchbase/src/io/lcb/mod.rs:74:14
stack backtrace:
```

For now, the workaround is just to `use bucket <bucket>` in the shell itself. I'm fine with that.

```bash
$ cbsh  # no bucket
👤 mcarifio at 🏠 default
> nodes
───┬─────────┬────────────────┬─────────┬──────────────────────────┬──────────────────────┬──────────────────────────┬──────────────┬─────────────
 # │ cluster │    hostname    │ status  │         services         │       version        │            os            │ memory_total │ memory_free 
───┼─────────┼────────────────┼─────────┼──────────────────────────┼──────────────────────┼──────────────────────────┼──────────────┼─────────────
 0 │ default │ 127.0.0.1:8091 │ healthy │ search,indexing,kv,query │ 6.6.0-7909-community │ x86_64-unknown-linux-gnu │      67.4 GB │     38.9 GB 
───┴─────────┴────────────────┴─────────┴──────────────────────────┴──────────────────────┴──────────────────────────┴──────────────┴─────────────
👤 mcarifio at 🏠 default
> use bucket mcarifio
───┬──────────
 # │  bucket  
───┼──────────
 0 │ mcarifio 
───┴──────────
👤 mcarifio at 🏠 default in 🗄  mcarifio
> nodes
───┬─────────┬────────────────┬─────────┬──────────────────────────┬──────────────────────┬──────────────────────────┬──────────────┬─────────────
 # │ cluster │    hostname    │ status  │         services         │       version        │            os            │ memory_total │ memory_free 
───┼─────────┼────────────────┼─────────┼──────────────────────────┼──────────────────────┼──────────────────────────┼──────────────┼─────────────
 0 │ default │ 127.0.0.1:8091 │ healthy │ search,indexing,kv,query │ 6.6.0-7909-community │ x86_64-unknown-linux-gnu │      67.4 GB │     38.9 GB 
───┴─────────┴────────────────┴─────────┴──────────────────────────┴──────────────────────┴───────
```

I don't know enough couch, rust, nushell or cbsh to hazard any hypothesis about why. 

Ty for `cbsh`. I'll continue to explore it.

**Comment by chvck** [comment]
Hi @mcarifio thanks for reporting this. I've had a look and can reproduce the `--bucket` flag not being respected. 

Setting the default-bucket in the config shouldn't be causing a panic though, in fact that's how I normally use the shell. In your config file I see tht you don't have a password set, have you just omitted that/are you using a separate credentials file? When I try to run with no password in the config (and no credentials file) the shell panics and won't start, which is another issue in itself.

**Comment by chvck** [comment]
The panic is to do with the bucket having the same name as the username. I think that there's some server legacy support for authenticating against a bucket directly, unsure how we're hooking into that yet but that seems to be the issue.

**Comment by mcarifio** [comment]
Good catch. I'll rename the bucket and give it a go later. In my config, I _do_ have a password, just didn't post it here. Appreciate the follow up @chvck, ty.

**Comment by chvck** [comment]
Any command line options specified will now be applied to the default active cluster from the config (the first cluster listed).

**Comment by daschl** [comment]
This should work with 1.0.0-alpha.1 as tested, please reopen if not.
